### PR TITLE
cleanup and setup

### PR DESCRIPTION
**Pull request by shahdivyank**

### CODE REVIEW

**Comment by shahdivyank** [comment]
Error is fine for now, issue is that the local dev expects the images in one place while the production build expects it elsewhere. Need to fix how the imports are done!

**Review by kobe-cb — APPROVED** [review]
Thank you.

**Review by edgar2020 — APPROVED** [review]
Asked to approve for practice

**Review by nicholastengbumroong — APPROVED** [review]
Approve practice

**Review by kirmar — APPROVED** [review]
Approved, thank you!

**Review by phamrachel17 — APPROVED** [review]

**Review by WinThant16 — APPROVED** [review]
Approve request practice

**Review by pondohoo — APPROVED** [review]
PR Practice

**Comment by Sarah-Rami27** [comment]
approved

**Review by Sarah-Rami27 — APPROVED** [review]

**Review by rfairooz — APPROVED** [review]
Approve Practice

**Review by SamuelLin213 — APPROVED** [review]
Approved for practice

**Review by advilm — APPROVED** [review]

**Review by SafeDuck — APPROVED** [review]

**Review by skyguy-netizen — APPROVED** [review]
Approved

**Review by Mandalorian49 — APPROVED** [review]
Approved

**Review by CJT578078 — APPROVED** [review]

**Review by vwong031 — APPROVED** [review]

**Review by msclal — APPROVED** [review]

**Review by MelanieGz — APPROVED** [review]

**Review by vraimondi04 — APPROVED** [review]

**Pull request merged**
